/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lmiQM2trkTp
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { DarkModeToggler } from "../DarkModeToggler/DarkModeToggler";

export function Navbar() {
  return (
    <header className="flex items-center justify-between px-6 py-4 bg-white dark:bg-gray-800">
      <h1 className="text-lg font-bold">GPrompTer Web</h1>
      <nav className="flex items-center space-x-4">
        <DarkModeToggler />
        <Link
          className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-100"
          href="/"
        >
          Home
        </Link>
        <Link
          className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-100"
          href="/prompts/new"
        >
          Add Prompt
        </Link>
      </nav>
    </header>
  );
}

function MoonIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
  );
}
